# Generated by Django 4.1.7 on 2023-03-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author_name",
            field=models.CharField(
                default="Author", max_length=255, verbose_name="Автор"
            ),
            preserve_default=False,
        ),
    ]
