# Generated by Django 4.1.7 on 2023-03-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_userbookrelation_options_book_readers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookrelation",
            name="rate",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ok"),
                    (2, "Fine"),
                    (3, "Good"),
                    (4, "Amazing"),
                    (5, "Incredible"),
                ],
                null=True,
                verbose_name="Оценка",
            ),
        ),
    ]
